### ISSUE TITLE
File attachment fails on mounted file systems

### ISSUE THREAD

**Issue by tmorrell** [caltechlibrary/dataset#1]
When running dataset on an a mounted file system, file attachment fails because of a cross-device link error.  

Error rename /var/folders/1v/4s1q6k890kbdd1zph2z9zbvh0000gp/T/239.tar446497925 caltechdata/aa/239.tar: cross-device link

**Comment by rsdoiel** [comment]
The storage package used in attachments.go has a os.Rename() in a call to fs.go at line 77. This needs to become a copy and delete to handle case of where Rename() fails do to cross system mounts.

**Comment by rsdoiel** [comment]
Fixed the Rename problem in storage/fs.go
