### ISSUE TITLE
filter/extract documentation

### ISSUE THREAD

**Issue by tmorrell** [caltechlibrary/dataset#15]
The filter command seems to have been replaced with extract, but there is no documentation

dataset init demo/mystuff
export DATASET=demo/mystuff
dataset create freda.json '{"name":"freda","email":"freda@inverness.example.org"}'
dataset filter '(eq .name "freda")'
do not understand filter

dataset extract '(eq "freda")' .name 
doesn't return a response

**Comment by rsdoiel** [comment]
I think this is a bug, probably I picked this up from an experimental I ran and didn't realize to got pulled into master.  I will fix this.

**Comment by rsdoiel** [comment]
Now this is coming back to my slow brain.  Filter migrated to keys (e.g. give me the record ids with Freda as a name), extract should return the unique values of a given dotpath.  I think I manange to step on some of the docs in my various branches and merges, I will make sure they get put back.

**Comment by rsdoiel** [comment]
fixed, added test to test_cmd. bash.
