### ISSUE TITLE
export-gsheet 404 message

### ISSUE THREAD

**Issue by tmorrell** [caltechlibrary/dataset#22]
dataset -overwrite import-gsheet "1SxEYlY9Hot8Q_NZccMVR4Yn6zI7I4syGEECNplS" Sheet1 "A1:Z" 1
Unable to retrieve data from sheet. googleapi: Error 404: Requested entity was not found., notFound

Error message should include name of sheet used to help user determine problem.

Not blocking

**Comment by rsdoiel** [comment]
Fixed.
