### ISSUE TITLE
dataset -json find

### ISSUE THREAD

**Issue by tmorrell** [caltechlibrary/dataset#35]
When no results are found, should return a json object indicating such.  

Prior response:

{"status":{"total":1,"failed":0,"successful":1},"request":{"query":{"query":"c.bleve +obj_id:*10.14291/tccon.ggg2014.reunion01.R0/1149"},"size":12,"from":0,"highlight":null,"fields":["*"],"facets":null,"explain":false,"sort":["-_score"],"includeLocations":false},"hits":[],"total_hits":0,"max_score":0,"took":25563279,"facets":{}}

**Comment by rsdoiel** [comment]
fixed in upcoming v0.032-dev release.
