### ISSUE TITLE
dataset attachments check

### ISSUE THREAD

**Issue by tmorrell** [caltechlibrary/dataset#4]
When attempting to attach files that do not exist, dataset accepts the command and returns OK.  This should return an error.

**Comment by rsdoiel** [comment]
I will add a check for key in collection before adding attachment in addAttachment(). I am renaming verb "detach" to "prune" and "attached" to "detach" per conversation.

**Comment by rsdoiel** [comment]
Fixed in v0.0.17-dev.

**Comment by rsdoiel** [comment]
Dev release v0.0.17-dev has fixes.

**Comment by tmorrell** [comment]
This fix is great! However we should also check if the file to be attached is present in the file system.

**Comment by rsdoiel** [comment]
Added check for attached file's exists before attaching as v0.0.18-dev
