### ISSUE TITLE
gsheet_export dotpath validation

### ISSUE THREAD

**Issue by tmorrell** [caltechlibrary/dataset#40]
In a recent release gsheet_export now verifies that the dotpath exists and returns the error 'failed to evaluate dot path, value not found'.  The prior behavior to not return anything for missing values allowed exporting of fields that might be filled in future versions of code.  Is it possible to have this return a warning instead of an error?

Alternatively, I could update my code to blank fill these fields and update my existing data set. Your thoughts appreciated.

**Comment by rsdoiel** [comment]
is fixed in upcoming v0.0.35 release.
