### ISSUE TITLE
use_strict_dotpath(False) behavior

### ISSUE THREAD

**Issue by tmorrell** [caltechlibrary/dataset#43]
use_strict_dotpath(False) seems to scramble the output of those columns in a way that doesn't make sense.  We might to just want to drop this option after improving the import-gsheet behavior

**Comment by rsdoiel** [comment]
Let me fix this.  I think I know where I made the error. I'll write some tests, make the change and if that works we'll keep this feature in the Python module.

**Comment by rsdoiel** [comment]
This is related to issue 44 and 45. Extract shouldn't throw error when dot path isn't available only when the collection cannot be accessed.
