### ISSUE TITLE
AWS_SDK_LOAD_CONFIG and Python

### ISSUE THREAD

**Issue by tmorrell** [caltechlibrary/dataset#48]
AWS_SDK_LOAD_CONFIG can't be set in the python environment.

For example:

```
import os
import dataset

os.environ['AWS_SDK_LOAD_CONFIG']="1"
collection = "s3://dataset.library.caltech.edu/CaltechDATA"
print(os.environ['AWS_SDK_LOAD_CONFIG'])
keys = dataset.keys(collection)
print(keys)
print(dataset.status(collection))
```

Fails, even though the correct environment variable prints.

Should return an error message about setting the environment variable in terminal.

**Comment by rsdoiel** [comment]
In the Go level code if the environment variable AWS_SDK_LOAD_CONFIG is not set it defaults to 1. If it is set (e.g. 0 or 1) then it is respected. The S3 tests will be run if the DATASET environment value holds a s3:// URI.
