### ISSUE TITLE
fields default in python version of find

### ISSUE THREAD

**Issue by tmorrell** [caltechlibrary/dataset#50]
The python version of find defaults to none versus all fields

Command line (json) response:

{"status":{"total":1,"failed":0,"successful":1},"request":{"query":{"query":"+obj_id:*10.14291/tccon.ggg2014.bremen01.R0/1149275"},"size":12,"from":0,"highlight":null,"fields":["*"],"facets":null,"explain":false,"sort":["-_score"],"includeLocations":false},"hits":[{"index":"data/crossref_refs.ds.bleve","id":"300b441c-76b0-4fb8-a538-df879b2cd044","score":9.962007209588313,"sort":["_score"],"fields":{"key":"300b441c-76b0-4fb8-a538-df879b2cd044","obj_id":"https://doi.org/10.14291/tccon.ggg2014.bremen01.R0/1149275","subj_id":"https://doi.org/10.3390/rs8050414"}},{"index":"data/crossref_refs.ds.bleve","id":"d42f91ff-3a5f-46f8-b423-2cbf361e8df0","score":9.962007209588313,"sort":["_score"],"fields":{"key":"d42f91ff-3a5f-46f8-b423-2cbf361e8df0","obj_id":"https://doi.org/10.14291/tccon.ggg2014.bremen01.R0/1149275","subj_id":"https://doi.org/10.3390/rs9101033"}}],"total_hits":2,"max_score":9.962007209588313,"took":27467604,"facets":{}}

Python response:

{'status': {'total': 1, 'failed': 0, 'successful': 1}, 'request': {'query': {'query': '+obj_id:*10.14291/tccon.ggg2014.karlsruhe01.R1/1182416'}, 'size': 12, 'from': 0, 'highlight': None, 'fields': None, 'facets': None, 'explain': False, 'sort': ['-_score'], 'includeLocations': False}, 'hits': [{'index': 'crossref_refs.ds.bleve', 'id': '72930d36-7283-4281-826a-10014a92f13f', 'score': 9.962007209588313, 'sort': ['_score']}, {'index': 'crossref_refs.ds.bleve', 'id': 'd0d4d1f7-2097-4083-bf84-783ac7d01d5a', 'score': 9.962007209588313, 'sort': ['_score']}], 'total_hits': 2, 'max_score': 9.962007209588313, 'took': 27432144, 'facets': {}}

**Comment by rsdoiel** [comment]
Added default of fields:"*" if options are not provided in the Python module.
