### ISSUE TITLE
Documentation cleanup

### ISSUE THREAD

**Issue by tmorrell** [caltechlibrary/dataset#6]
Attachment response format for attached

**Comment by tmorrell** [comment]
Clean up examples in README
Remove any examples that include filter command
Check DOI image formatting
Check Nav.md linking
Consider putting topics list on front page of program and moving examples to linked page

**Comment by rsdoiel** [comment]
Normalized JSON_RECORD_ID and KEY to KEY in docs.

**Comment by rsdoiel** [comment]
Need to normalize the phrase "JSON document" and "JSON record". It sounds like we're talking about two different things when we are talking about the same thing.

**Comment by rsdoiel** [comment]
The how-tos need serious work and we might just want to toss some of them in favor of a comprehensive re-org/re-write sprint.

**Comment by tmorrell** [comment]
Add -overwrite to import-gsheet

**Comment by tmorrell** [comment]
Syntax
    dataset [OPTIONS] COLLECTION_NAME indexer INDEX_NAME INDEX_MAP_FILENAME

INDEX_NAME and NDEX_MAP_FILENAME should be flipped

**Comment by rsdoiel** [comment]
I've updated the command so the filename ending with .bleve will be assigned as the index name, the other one provided will be treated as the map filename.

**Comment by rsdoiel** [comment]
Pushed documentation changes and update with v0.0.32-dev release.

**Comment by rsdoiel** [comment]
Lot's of changes will impact the docs in the v0.0.47 release.

Let's of updates with the new cli implementation. With the updates done in storage and cli Go packages as well as the full integration of the verb metaphor in the dataset cli itself the doc examples are surely out of sync.  The basic command documentation we can re-generate from the cli itself (e.g. dataset -generate-markdown, dataset -generate-manpage) but the examples and more detailed concept pages need to be reviewed and examples need to be tested and updated where needed.

**Comment by rsdoiel** [comment]
I'm going to close this issue in favor of creating an issue type "doc bug" with all the changes in behavior that the v0.0.47 release caused.
