### ISSUE TITLE
Documentation help for Google Sheets and cloud storage

### ISSUE THREAD

**Issue by rsdoiel** [caltechlibrary/dataset#60]
In the how-to directory the documentation on Cloud Storage (e.g. S3 and Google Cloud Storage) is incomplete. No Python examples have been written and the whole thing probable should be rewritten anyway. Likewise the Google Sheets page only has a paragraph and a FIXME note.

- how-to/working-with-cloud-storage.md
- how-to/working-with-gsheets.md

**Comment by rsdoiel** [comment]
The following also need rewriting or are missing Python documentation

- how-to/file-system-layout.md
- how-to/filtering-keys.md (should key filtering remain as a feature in dataset? or should that happen outside ataset? e.g. should this be a topic of using datatools plus dataset? or writing a Python script?)
- how-to/joining-objects.md
- how-to/managing-attachments.md (needs Python plus some better use case examples)
- how-to/reshaping-json-collections.md (needs Python examples, should this be under the heading of using dataset with datatools?)
- how-to/taking-samples.md (needs Python example, probably needs to be better integrated with cloning-and-samples.md)

**Comment by rsdoiel** [comment]
A first draft of working-with-gsheets.md is now deloyed. Lots of ruff edges, could use a few more (or better) screen shots.

**Comment by rsdoiel** [comment]
This all needs to be revisited before the v1.0.0 release.  We need documentation for both the dataset cli as well as the Python module implementation.

**Comment by tmorrell** [comment]
Need to confirm acceptable locations for credentials.json and verify in documentation

**Comment by rsdoiel** [comment]
Google Sheet support has been dropped as of v0.1.8.
