### ISSUE TITLE
S3 bug between 0.0.46, 0.0.45 and Feeds

### ISSUE THREAD

**Issue by tmorrell** [caltechlibrary/dataset#65]
dataset -c s3://dataset.library.caltech.edu/CaltechDATA keys

returns

Bucket not defined for CaltechDATA/collection.json

**Comment by tmorrell** [comment]
Works fine in 0.0.43

**Comment by rsdoiel** [comment]
I believe this has been solved in the upcoming v0.0.47, I am going to close this issue now and we can re-open it if it crops up again.
