### ISSUE TITLE
dsfind default fields

### ISSUE THREAD

**Issue by tmorrell** [caltechlibrary/dataset#7]
dsfind default may not include all fields-possibly related to fields that are arrays:

dsfind authors.bleve authors:Stone-E-C
2 matches, showing 1 through 2, took 215.031µs

dsfind authors.bleve Stone-E-C
No matches

dsfind authors.bleve "Stone-E-C"
No matches

[authors.bleve.zip](https://github.com/caltechlibrary/dataset/files/1704109/authors.bleve.zip)
[authors.json.zip](https://github.com/caltechlibrary/dataset/files/1704112/authors.json.zip)

**Comment by rsdoiel** [comment]
Issue 8 changes the index definition to match Bleve's native index definition. We loose the ability to alias fieldnames (e.g. creators[:].id as authors_id) but gain correct handling of sub field indexing as well as the ability to define faceted indexes. See issue_8 changes.
