### ISSUE TITLE
error in cli help

### ISSUE THREAD

**Issue by atomotic** [caltechlibrary/dataset#74]
https://github.com/caltechlibrary/dataset/blob/e9d0a0a3a4ec0f79dba87b8ba6842cb222e34d8b/cmd/dataset/dataset.go#L84

`dataset friends.ds create` should be `dataset create friends.ds`

**Comment by rsdoiel** [comment]
Thanks, I missed this change. I will fix it.

- Robert

**Comment by rsdoiel** [comment]
Fix should show up in next release.

All the best,

Robert
