### ISSUE TITLE
Python wrapper for sync-send and sync-receive

### ISSUE THREAD

**Issue by tmorrell** [caltechlibrary/dataset#80]
Add python wrapper for gsheet sync-send and sync-receive

**Comment by rsdoiel** [comment]
Adding four methods, sync_send_csv, sync_recieve_csv, sync_send_gsheet, sync_recieve_gsheet to libdataset.go. Once I've debugged these I will wrap them in the Python module for dataset.

**Comment by rsdoiel** [comment]
Fixed command line bug in cli for sync-receive (always wrote to stdout event which specifying CSV filename). Fixed GSheet tests. Added sync_send_csv, sync_send_gsheet, sync_recieve_csv, sync_recieve_gsheet. Changes will be reflected in v0.0.52 release.
