### ISSUE TITLE
Case handling issues when writing paths

### ISSUE THREAD

**Issue by rsdoiel** [caltechlibrary/dataset#81]
Moving from Linux where most OS are case sensitive to Mac OS X where they might be causes issues for moving content via zipped collections. E.g. If COLLETION_NAME/pairtree/de path exists and you try to write COLLECTION_NAME/pairtree/De there is a collisions that prevents the case sensitive path from being unzipped properly. Not particularly a dataset issue BUT something to document for people who move collections via ZIP.

**Comment by rsdoiel** [comment]
This is a problem for dataset command. If the path exists for keys with one case and you later create a record with the same prefix but different case Mac OS X will treat the two paths as the same.

When unzipped (or untarred) on Linux the following dataset collections records were broken.

```
2019/04/02 12:35:02 ERROR: Deser-S is missing ("people.ds/pairtree/De/se/r-/S")
2019/04/02 12:35:02 ERROR: Desbrun-M is missing ("people.ds/pairtree/De/sb/ru/n-/M")
2019/04/02 12:35:02 ERROR: Dervan-P-B is missing ("people.ds/pairtree/De/rv/an/-P/-B")
2019/04/02 12:35:02 ERROR: von-Kármán-Th is missing ("people.ds/pairtree/vo/n-/Ká/rm/án/-T/h")
2019/04/02 12:35:02 ERROR: Deshaies-R-J is missing ("people.ds/pairtree/De/sh/ai/es/-R/-J")
2019/04/02 12:35:02 ERROR: Dean-Richard-A is missing ("people.ds/pairtree/De/an/-R/ic/ha/rd/-A")
2019/04/02 12:35:02 ERROR: Demirel-Frank-S is missing ("people.ds/pairtree/De/mi/re/l-/Fr/an/k-/S")
2019/04/02 12:35:02 ERROR: Desharnais-Robert-A is missing ("people.ds/pairtree/De/sh/ar/na/is/-R/ob/er/t-/A")
```

On Mac OS X they had been seen as existing since Mac OX X file system treated people.ds/De/... and people.ds/de/.. as the same path before returning path not found.

**Comment by rsdoiel** [comment]
Here's how a record looks to the dataset and to Mac OS X.

```
datawork@datawork:/Sites/feeds.library.caltech.edu $ dataset path people.ds Demetriou-M-D
people.ds/pairtree/De/me/tr/io/u-/M-/D/Demetriou-M-D.json
datawork@datawork:/Sites/feeds.library.caltech.edu $ tree people.ds/pairtree/
Display all 183 possibilities? (y or n)
datawork@datawork:/Sites/feeds.library.caltech.edu $ tree people.ds/pairtree/de/ 
-B/ an/ lb/ me/ mi/ nn/ rv/ sb/ se/ sh/ 
datawork@datawork:/Sites/feeds.library.caltech.edu $ tree people.ds/pairtree/de/me/tr/io/u-/M-/D/
people.ds/pairtree/de/me/tr/io/u-/M-/D/
└── Demetriou-M-D.json

0 directories, 1 file
```

**Comment by rsdoiel** [comment]
From the dataset point of view this is problematic at the Go level. There seems to be a divergence of opinion to most pushing to the file system level to deal with this issue.  Possible solutions

+ advise people how to setup their Mac to work as case sensitive if they plan to move collections between OS (ugly solution)
+ provide a safe archive verb in dataset (seems like overkill) so files written to zip or tar ball are written with a proper path in the pairtree
+ have multiple checks for path variation before giving up on finding the record (very ugly and slow)
+ add support in "repair" to handle reconciling what is in collection.json and what was the legacy path (ugly)

Plus one point for Mac OS X being an unnecessary pain.

**Comment by rsdoiel** [comment]
Decided to implement fix in pairtreeRepair func. It's ugly but does resolve the issue of loss records for now. It might make sense to implement a "archive" verb that allows for portable collections so you don't have to run repair all the time.

**Comment by tmorrell** [comment]
+1 on new functionality to archive or bag collection in dataset

**Comment by rsdoiel** [comment]
I think this is the long term solution but I am going to add the verb as a separate issue. Thanks, RSD
