### ISSUE TITLE
Update docs, examples and help on frames and attachments

### ISSUE THREAD

**Issue by rsdoiel** [caltechlibrary/dataset#92]
With release v0.0.64 the DataFrame has changed structure and funcs related to frames, grids and attachments have changed signatures. These need to be reflected in the help, docs and examples.

**Comment by tmorrell** [comment]
https://caltechlibrary.github.io/dataset/docs/frame.html needs some updates

**Comment by rsdoiel** [comment]
Documentation has been updated
