### ISSUE TITLE
Does an ObjectList really need to enforce ._Key and _Key labels?

### ISSUE THREAD

**Issue by rsdoiel** [caltechlibrary/dataset#94]
Been re-thinking the implications of changing from a Grid to ObjectList. In the Frame metadata we have keys, labels and dot paths. We can regenerate the ObjectList with those things. Do we need to enforce having the records' key embedded in each object of an ObjectList?  One use case for Frames is restructuring data for synchronization with spreadsheets. The spreadsheet may not need a "_Key" column heading and it maybe a problem (e.g. they've called the unique ID column "fred" as an example, not "_Key"). In this scenario we might share a common key between the collection and spreadsheet but use different names.  If so we should allow the objects in the ObjectList to be structured to match the spreadsheet columns. We can update the related object in our collection by taking the index value from ObjectList and matching that to the key associated with that index value. This does break down when you add content via the spreadsheet that has not been added to the collection. But that might be resolvable requiring the object to have a unique ID (not necessarily the ID in the collection) as the first column and having a mechanism to create a new ID auto-magically in the collection (e.g. like an auto-increment field in SQL table or the internal ID used in MongoDB based on sequence as well as running instance).

**Comment by tmorrell** [comment]
Agreed that since we're providing a list of keys, _Key doesn't need to be in the ObjectList

**Comment by rsdoiel** [comment]
I was also thinking that I can drop the “label” command  and function, especially as we have a nice object approach that maps good between the command line and Python library.  Moving from 2D array to list of Objects makes the “label” command expensive, it’s the same over head as making a new frame as each object must be touched and in my current implementation gets updated from the current state of the collection. Then there is also one thing less to document. :-)

Thanks,

Robert

**Comment by rsdoiel** [comment]
I've kept both dot_paths and labels in the frame object. It's useful for mapping one path to another. E.g. in EPrints .lastmod is useful to have named .updated in the frame to to make the frame output compatible with invenio.  Labels really serve two purposes, nice human friendly labels in a table output or more useful, a mapping of names to object attributes in the saved object list.
