### ISSUE TITLE
Empty attachments

### ISSUE THREAD

**Issue by tmorrell** [caltechlibrary/dataset#96]
There still seems to be an issue with empty attachments in v0.0.67

Steps: 
dataset -v
dataset v0.0.67
dataset init test.ds
OK
dataset create test.ds 123 '{"name":"Jane Doe"}'
OK
dataset attach test.ds 123 codemeta.json

dataset attachments test.ds 123
codemeta.json 1149
dataset detach test.ds 123
OK

The detached codemeta.json file is empty

**Comment by rsdoiel** [comment]
Hah, found the same error I made with streams.  I read the content into one variable and didn't attach the results to the attachment object. I'll compile, double check and then do another release with the fix. Thanks for finding this!
