### ISSUE TITLE
Google sheet export fails when sheet name doesn't exist

### ISSUE THREAD

**Issue by tmorrell** [caltechlibrary/dataset#97]
Google sheet export or sync fails if the sheet name had not been created manually in the document beforehand.  From the API documentation it's not clear how easy this would be to automate.

Unable to write sheet 40747!A1:CZ. googleapi: Error 400: Unable to parse range: 40747!A1:CZ, badReques

**Comment by rsdoiel** [comment]
Dropped support for Google Sheets, S3 and Google Cloud storage.
