### ISSUE TITLE
Attachments not listed after update

### ISSUE THREAD

**Issue by tmorrell** [caltechlibrary/dataset#98]
Attachments are not longer listed after an update command is run. The attached files are still in the collection, but the _Attachments metadata is deleted during the update.

Testing:

dataset init test.ds
OK
dataset create test.ds 123 '{"key":"value"}'
OK
dataset attach test.ds 123 greer.html

dataset attachments test.ds 123
greer.html 133
dataset update test.ds 123 '{"key":"value2"}'
OK
dataset attachments test.ds 123

**Comment by rsdoiel** [comment]
I have a fix in the v0.1.2 release (master) but will need to back port the fix to our v0.0.x series.

**Comment by rsdoiel** [comment]
This is corrected in v0.1.2.
